name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:   # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2.13.0

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --web-renderer canvaskit

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
        publish_branch: webpage
        
